# Generated by Django 5.0.6 on 2024-05-29 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='model_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='model_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='model_id',
            new_name='id',
        ),
    ]
