# Generated by Django 5.0.6 on 2024-05-27 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0002_rename_categories_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(db_column='categories_id', on_delete=django.db.models.deletion.CASCADE, to='blogapi.category'),
        ),
    ]
