# Generated by Django 5.0.6 on 2024-05-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0004_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(default='https://webneel.com/daily/sites/default/files/images/daily/08-2018/1-nature-photography-spring-season-mumtazshamsee.jpg', upload_to='post_banners/'),
        ),
    ]
